import { Video, NotificationItem, CategoryName } from '../types';

export const CATEGORIES: CategoryName[] = [
  'Technology',
  'Programming',
  'Business',
  'Education',
  'Motivation',
  'Islam',
  'Entertainment',
  'Science',
  'Health',
  'Finance',
  'News'
];

export const SEED_VIDEOS: Video[] = [
  {
    id: 'tech-1',
    title: 'The Next Wave of Quantum Computing & AI Hardware',
    description: 'An in-depth exploration of how quantum processors and photonic AI chips are reshaping computing architecture in 2026. Published exclusively by StreamMind System Admin.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
    category: 'Technology',
    tags: ['Quantum Computing', 'AI Hardware', 'Semiconductors', 'Future Tech'],
    duration: '14:20',
    durationSeconds: 860,
    views: 142500,
    likesCount: 12400,
    savesCount: 3100,
    publishedAt: '2026-06-25T10:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isFeatured: true,
    isTrending: true
  },
  {
    id: 'prog-1',
    title: 'Modern Next.js 16 & React Server Components Deep Dive',
    description: 'Master asynchronous components, streaming SSR, and suspense architecture with production-grade TypeScript patterns. A must-watch for fullstack developers.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    category: 'Programming',
    tags: ['React', 'Next.js', 'TypeScript', 'Web Development'],
    duration: '28:45',
    durationSeconds: 1725,
    views: 289000,
    likesCount: 31200,
    savesCount: 9400,
    publishedAt: '2026-06-24T14:30:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isTrending: true
  },
  {
    id: 'biz-1',
    title: 'Building a $10M ARR SaaS: Bootstrap vs Venture Capital',
    description: 'Strategic analysis of capital allocation, unit economics, customer acquisition cost (CAC), and retention metrics for B2B software startup founders.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    tags: ['SaaS', 'Startups', 'Venture Capital', 'Business Strategy'],
    duration: '19:10',
    durationSeconds: 1150,
    views: 98400,
    likesCount: 8900,
    savesCount: 4200,
    publishedAt: '2026-06-22T09:15:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isFeatured: true
  },
  {
    id: 'islam-1',
    title: 'Finding Inner Peace & Mindfulness in Daily Salah (নামাজে শান্তি)',
    description: 'An inspiring Islamic lecture discussing spiritual connection, khushu (presence of heart), and stress relief through authentic prayer practices. Bilingual commentary.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&auto=format&fit=crop&q=80',
    category: 'Islam',
    tags: ['Islam', 'Salah', 'Mindfulness', 'Spiritual', 'বাংলা'],
    duration: '22:15',
    durationSeconds: 1335,
    views: 310500,
    likesCount: 45000,
    savesCount: 18200,
    publishedAt: '2026-06-26T06:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isFeatured: true,
    isTrending: true
  },
  {
    id: 'fin-1',
    title: 'Index Funds & Compound Interest: Beginner Guide to Financial Freedom',
    description: 'Understand global ETFs, dollar-cost averaging, inflation hedging, and wealth accumulation principles without taking reckless stock picking risks.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&auto=format&fit=crop&q=80',
    category: 'Finance',
    tags: ['Investing', 'Index Funds', 'Personal Finance', 'Wealth'],
    duration: '16:50',
    durationSeconds: 1010,
    views: 215000,
    likesCount: 19800,
    savesCount: 8100,
    publishedAt: '2026-06-20T11:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isTrending: true
  },
  {
    id: 'mot-1',
    title: 'The Discipline Blueprint: Overcoming Procrastination & Dopamine Fatigue',
    description: 'Neuroscience-backed daily routines to rebuild deep focus, eliminate distraction loops, and execute high-stakes personal goals consistently.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    category: 'Motivation',
    tags: ['Discipline', 'Productivity', 'Mindset', 'Neuroscience'],
    duration: '12:30',
    durationSeconds: 750,
    views: 178000,
    likesCount: 22100,
    savesCount: 7500,
    publishedAt: '2026-06-23T16:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'edu-1',
    title: 'How mRNA Vaccines & Gene Editing (CRISPR) Cure Genetic Disorders',
    description: 'Clear educational animation breaking down CRISPR-Cas9 molecular scissors, cell therapy breakthroughs, and modern biomedical engineering.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80',
    category: 'Education',
    tags: ['Biology', 'CRISPR', 'Genetics', 'Medicine', 'Science'],
    duration: '15:40',
    durationSeconds: 940,
    views: 89000,
    likesCount: 9100,
    savesCount: 3400,
    publishedAt: '2026-06-19T08:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'sci-1',
    title: 'James Webb Space Telescope: Discovering the First Galaxies at the Dawn of Time',
    description: 'Breathtaking infrared survey images revealing exoplanet atmospheres, dark matter webs, and deep cosmic structures formed 13.8 billion years ago.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    category: 'Science',
    tags: ['Astronomy', 'Space', 'Physics', 'Cosmology'],
    duration: '24:00',
    durationSeconds: 1440,
    views: 340000,
    likesCount: 41000,
    savesCount: 15600,
    publishedAt: '2026-06-25T18:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isTrending: true
  },
  {
    id: 'health-1',
    title: 'Longevity Science: Zone 2 Cardio, Sleep Architecture & Metabolic Health',
    description: 'Evidence-based protocols from leading physicians on improving mitochondrial efficiency, slow-wave sleep cycles, and insulin sensitivity.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop&q=80',
    category: 'Health',
    tags: ['Fitness', 'Longevity', 'Cardio', 'Health Optimization'],
    duration: '21:10',
    durationSeconds: 1270,
    views: 112000,
    likesCount: 14300,
    savesCount: 6200,
    publishedAt: '2026-06-21T12:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'ent-1',
    title: 'Cinematic Visual Effects & Unreal Engine 5.5 Virtual Production',
    description: 'Behind the scenes of how Hollywood blockbusters use real-time LED volumes and raytraced rendering pipelines to eliminate green screens.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80',
    category: 'Entertainment',
    tags: ['Filmmaking', 'VFX', 'Unreal Engine', 'Cinema'],
    duration: '18:30',
    durationSeconds: 1110,
    views: 195000,
    likesCount: 18400,
    savesCount: 4100,
    publishedAt: '2026-06-18T15:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'news-1',
    title: 'Global Tech Policy Report: AI Regulation & Renewable Energy Grids',
    description: 'Comprehensive analysis of international treaties governing autonomous systems and clean energy grid investments across Asia and North America.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&auto=format&fit=crop&q=80',
    category: 'News',
    tags: ['Global News', 'Policy', 'AI Regulation', 'Energy'],
    duration: '11:45',
    durationSeconds: 705,
    views: 74000,
    likesCount: 5200,
    savesCount: 1100,
    publishedAt: '2026-06-26T14:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'tech-2',
    title: 'Autonomous Robotics & Humanoid AI Factory Assistants',
    description: 'How neural network vision models allow bipedal humanoid robots to perform delicate assembly line maneuvers and household tasks autonomously.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    category: 'Technology',
    tags: ['Robotics', 'Humanoid', 'AI', 'Automation'],
    duration: '16:00',
    durationSeconds: 960,
    views: 154000,
    likesCount: 16200,
    savesCount: 4500,
    publishedAt: '2026-06-23T10:30:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'prog-2',
    title: 'Python FastAPI vs Node Express: Backend Benchmark 2026',
    description: 'Extreme concurrency load testing comparison evaluating throughput, serialization speed, and memory footprint under 100k requests/sec.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    category: 'Programming',
    tags: ['Python', 'FastAPI', 'Node.js', 'Backend', 'Performance'],
    duration: '20:15',
    durationSeconds: 1215,
    views: 182000,
    likesCount: 21000,
    savesCount: 5800,
    publishedAt: '2026-06-20T09:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'islam-2',
    title: 'Life of Prophet Muhammad (ﷺ): Lessons of Compassion & Leadership',
    description: 'Historical reflection on timeless principles of mercy, diplomacy, truthfulness, and community building from the Seerah. Narrated with profound clarity.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800&auto=format&fit=crop&q=80',
    category: 'Islam',
    tags: ['Seerah', 'Islam', 'History', 'Prophet Muhammad', 'লেকচার'],
    duration: '35:20',
    durationSeconds: 2120,
    views: 420000,
    likesCount: 62000,
    savesCount: 24000,
    publishedAt: '2026-06-22T04:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isFeatured: true
  },
  {
    id: 'biz-2',
    title: 'Product-Market Fit Mastery: Conducting Customer Discovery Interviews',
    description: 'Learn the Mom Test framework to extract honest feedback from potential buyers before writing a single line of code or wasting engineering budgets.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1552581234-26160f608093?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    tags: ['Product Management', 'Startups', 'Marketing', 'Interviews'],
    duration: '17:40',
    durationSeconds: 1060,
    views: 65000,
    likesCount: 7100,
    savesCount: 3800,
    publishedAt: '2026-06-17T13:00:00Z',
    channelName: 'StreamMind Admin',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '✨ Welcome to StreamMind!',
    message: 'Explore our AI-curated video catalog published exclusively by verified platform administrators.',
    type: 'system',
    createdAt: new Date().toISOString(),
    read: false
  },
  {
    id: 'notif-2',
    title: '🔥 Trending Now: Quantum AI',
    message: '"The Next Wave of Quantum Computing & AI Hardware" is gaining massive momentum today.',
    type: 'trending',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    read: false,
    videoId: 'tech-1'
  },
  {
    id: 'notif-3',
    title: '💡 Smart AI Assistant Ready',
    message: 'Try asking our conversational assistant in English or বাংলা for personalized recommendations.',
    type: 'recommendation',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    read: false
  }
];
